import type { ScenarioFormValues } from '../../api/modules/types';

export const defaultScenario: ScenarioFormValues = {
  name: 'Novo cenário',
  broker: 'KAFKA',
  ratePerSecond: 200,
  consumers: 4,
  processingMs: 15,
  failurePct: 1,
  maxRetries: 3,
  messageSizeKb: 2,
  durationSeconds: 120,
  queueCapacity: null,
  partitions: 6,
  visibilityTimeoutSeconds: 30,
  retentionHours: 168,
  retentionMb: 256,
  highWatermarkMb: 256,
  prefetch: 250,
  inflightMax: 120000,
  dlqEnabled: true,
  burstEnabled: false,
  executionMode: 'SIMULATED',
  serviceProfile: 'EXPONENTIAL',
};
